const test = require('node:test')
const assert = require('node:assert/strict')
const { EventEmitter } = require('node:events')
const { ConnectionRegistry } = require('../src/connection/registry')
const { createDispatcher } = require('../src/message/dispatcher')

test('connection registries keep independent connection and lifecycle state', t => {
  const first = new ConnectionRegistry()
  const second = new ConnectionRegistry()
  t.after(() => { first.close(); second.close() })
  first.attach(createDispatcher())
  second.attach(createDispatcher())
  const connection = Object.assign(new EventEmitter(), { ping() {}, terminate() {} })
  first.addConnection(connection)
  assert.deepEqual(first.getConnections(), [connection])
  assert.deepEqual(second.getConnections(), [])
  first.close()
  assert.deepEqual(first.getConnections(), [])
  assert.notEqual(second.healthCheckInterval._destroyed, true)
})
