#
# mindflayer-server Dockerfile
#
# https://github.com/mindflayer-vtt/mindflayer-server
#

# Add some build args
ARG NODE_VERSION=24-alpine

# Use the supported Node 24 LTS base image
FROM node:$NODE_VERSION

# Required only for first-start self-signed certificate creation. The durable
# private key is generated by Node and remains in the mounted data directory.
RUN apk add --no-cache openssl

# Run in production mode
ENV NODE_ENV=production
ENV MINDFLAYER_DATA_DIR=/data
ENV MINDFLAYER_FIRMWARE_DIR=/firmware

# Switch to /app directory
WORKDIR /app

# Copy dependency manifests separately so installs can be cached
COPY --chown=node:node package.json package-lock.json ./

# Install the server dependencies
RUN \
  apk add --update --no-cache --virtual .gyp-fix \
    g++ \
    make \
    python3 \
    git && \
  npm ci --omit=dev && \
  apk del .gyp-fix

# Copy only runtime files. Keeping this allowlist explicit prevents local data,
# credentials, tests, and host-native node_modules from entering the image.
COPY --chown=node:node src ./src
COPY --chown=node:node static ./static
COPY --chown=node:node scripts ./scripts
RUN mkdir -p /data /firmware && chown node:node /data /firmware

# Run the server without root privileges
USER node

# Foundry traffic is plain HTTP/WS for a browser-trusted reverse proxy. Keypads
# connect directly to the separate TLS listener.
EXPOSE 8080 10443
VOLUME [ "/data" ]

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD [ "node", "scripts/healthcheck.js" ]

# Start the server
CMD [ "npm", "start" ]
